# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import authentication_pb2 as authentication__pb2


class AuthenticationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.viaAuthCode = channel.unary_unary(
                '/web.authentication.Authentication/viaAuthCode',
                request_serializer=authentication__pb2.AuthRequest.SerializeToString,
                response_deserializer=authentication__pb2.AuthResponse.FromString,
                )
        self.logout = channel.unary_unary(
                '/web.authentication.Authentication/logout',
                request_serializer=authentication__pb2.Empty.SerializeToString,
                response_deserializer=authentication__pb2.Empty.FromString,
                )


class AuthenticationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def viaAuthCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'viaAuthCode': grpc.unary_unary_rpc_method_handler(
                    servicer.viaAuthCode,
                    request_deserializer=authentication__pb2.AuthRequest.FromString,
                    response_serializer=authentication__pb2.AuthResponse.SerializeToString,
            ),
            'logout': grpc.unary_unary_rpc_method_handler(
                    servicer.logout,
                    request_deserializer=authentication__pb2.Empty.FromString,
                    response_serializer=authentication__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'web.authentication.Authentication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Authentication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def viaAuthCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.authentication.Authentication/viaAuthCode',
            authentication__pb2.AuthRequest.SerializeToString,
            authentication__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.authentication.Authentication/logout',
            authentication__pb2.Empty.SerializeToString,
            authentication__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
