# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import communitygames_pb2 as communitygames__pb2


class CommunityGamesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createPlayground = channel.unary_unary(
                '/web.communitygames.CommunityGames/createPlayground',
                request_serializer=communitygames__pb2.CreatePlaygroundRequest.SerializeToString,
                response_deserializer=communitygames__pb2.CreatePlaygroundResponse.FromString,
                )
        self.updatePlayground = channel.unary_unary(
                '/web.communitygames.CommunityGames/updatePlayground',
                request_serializer=communitygames__pb2.UpdatePlaygroundRequest.SerializeToString,
                response_deserializer=communitygames__pb2.UpdatePlaygroundResponse.FromString,
                )
        self.deletePlayground = channel.unary_unary(
                '/web.communitygames.CommunityGames/deletePlayground',
                request_serializer=communitygames__pb2.DeletePlaygroundRequest.SerializeToString,
                response_deserializer=communitygames__pb2.DeletePlaygroundResponse.FromString,
                )
        self.getPlayground = channel.unary_unary(
                '/web.communitygames.CommunityGames/getPlayground',
                request_serializer=communitygames__pb2.GetPlaygroundRequest.SerializeToString,
                response_deserializer=communitygames__pb2.PlaygroundInfoResponse.FromString,
                )
        self.listPlaygroundsByOwner = channel.unary_unary(
                '/web.communitygames.CommunityGames/listPlaygroundsByOwner',
                request_serializer=communitygames__pb2.ListPlaygroundsByOwnerRequest.SerializeToString,
                response_deserializer=communitygames__pb2.ListPlaygroundsByOwnerResponse.FromString,
                )
        self.getBlueprintsById = channel.unary_unary(
                '/web.communitygames.CommunityGames/getBlueprintsById',
                request_serializer=communitygames__pb2.GetBlueprintsByIdRequest.SerializeToString,
                response_deserializer=communitygames__pb2.GetBlueprintsByIdResponse.FromString,
                )
        self.getScheduledBlueprints = channel.unary_unary(
                '/web.communitygames.CommunityGames/getScheduledBlueprints',
                request_serializer=communitygames__pb2.GetScheduledBlueprintsRequest.SerializeToString,
                response_deserializer=communitygames__pb2.GetScheduledBlueprintsResponse.FromString,
                )
        self.getConstraints = channel.unary_unary(
                '/web.communitygames.CommunityGames/getConstraints',
                request_serializer=communitygames__pb2.GetConstraintsRequest.SerializeToString,
                response_deserializer=communitygames__pb2.GetConstraintsResponse.FromString,
                )
        self.sharePlayground = channel.unary_unary(
                '/web.communitygames.CommunityGames/sharePlayground',
                request_serializer=communitygames__pb2.SharePlaygroundRequest.SerializeToString,
                response_deserializer=communitygames__pb2.SharePlaygroundResponse.FromString,
                )
        self.getProgressionTypes = channel.unary_unary(
                '/web.communitygames.CommunityGames/getProgressionTypes',
                request_serializer=communitygames__pb2.GetProgressionTypesRequest.SerializeToString,
                response_deserializer=communitygames__pb2.GetProgressionTypesResponse.FromString,
                )


class CommunityGamesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createPlayground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updatePlayground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deletePlayground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPlayground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listPlaygroundsByOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBlueprintsById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getScheduledBlueprints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getConstraints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sharePlayground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProgressionTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunityGamesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createPlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.createPlayground,
                    request_deserializer=communitygames__pb2.CreatePlaygroundRequest.FromString,
                    response_serializer=communitygames__pb2.CreatePlaygroundResponse.SerializeToString,
            ),
            'updatePlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.updatePlayground,
                    request_deserializer=communitygames__pb2.UpdatePlaygroundRequest.FromString,
                    response_serializer=communitygames__pb2.UpdatePlaygroundResponse.SerializeToString,
            ),
            'deletePlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.deletePlayground,
                    request_deserializer=communitygames__pb2.DeletePlaygroundRequest.FromString,
                    response_serializer=communitygames__pb2.DeletePlaygroundResponse.SerializeToString,
            ),
            'getPlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.getPlayground,
                    request_deserializer=communitygames__pb2.GetPlaygroundRequest.FromString,
                    response_serializer=communitygames__pb2.PlaygroundInfoResponse.SerializeToString,
            ),
            'listPlaygroundsByOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.listPlaygroundsByOwner,
                    request_deserializer=communitygames__pb2.ListPlaygroundsByOwnerRequest.FromString,
                    response_serializer=communitygames__pb2.ListPlaygroundsByOwnerResponse.SerializeToString,
            ),
            'getBlueprintsById': grpc.unary_unary_rpc_method_handler(
                    servicer.getBlueprintsById,
                    request_deserializer=communitygames__pb2.GetBlueprintsByIdRequest.FromString,
                    response_serializer=communitygames__pb2.GetBlueprintsByIdResponse.SerializeToString,
            ),
            'getScheduledBlueprints': grpc.unary_unary_rpc_method_handler(
                    servicer.getScheduledBlueprints,
                    request_deserializer=communitygames__pb2.GetScheduledBlueprintsRequest.FromString,
                    response_serializer=communitygames__pb2.GetScheduledBlueprintsResponse.SerializeToString,
            ),
            'getConstraints': grpc.unary_unary_rpc_method_handler(
                    servicer.getConstraints,
                    request_deserializer=communitygames__pb2.GetConstraintsRequest.FromString,
                    response_serializer=communitygames__pb2.GetConstraintsResponse.SerializeToString,
            ),
            'sharePlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.sharePlayground,
                    request_deserializer=communitygames__pb2.SharePlaygroundRequest.FromString,
                    response_serializer=communitygames__pb2.SharePlaygroundResponse.SerializeToString,
            ),
            'getProgressionTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.getProgressionTypes,
                    request_deserializer=communitygames__pb2.GetProgressionTypesRequest.FromString,
                    response_serializer=communitygames__pb2.GetProgressionTypesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'web.communitygames.CommunityGames', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommunityGames(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createPlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/createPlayground',
            communitygames__pb2.CreatePlaygroundRequest.SerializeToString,
            communitygames__pb2.CreatePlaygroundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updatePlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/updatePlayground',
            communitygames__pb2.UpdatePlaygroundRequest.SerializeToString,
            communitygames__pb2.UpdatePlaygroundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deletePlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/deletePlayground',
            communitygames__pb2.DeletePlaygroundRequest.SerializeToString,
            communitygames__pb2.DeletePlaygroundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/getPlayground',
            communitygames__pb2.GetPlaygroundRequest.SerializeToString,
            communitygames__pb2.PlaygroundInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listPlaygroundsByOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/listPlaygroundsByOwner',
            communitygames__pb2.ListPlaygroundsByOwnerRequest.SerializeToString,
            communitygames__pb2.ListPlaygroundsByOwnerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getBlueprintsById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/getBlueprintsById',
            communitygames__pb2.GetBlueprintsByIdRequest.SerializeToString,
            communitygames__pb2.GetBlueprintsByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getScheduledBlueprints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/getScheduledBlueprints',
            communitygames__pb2.GetScheduledBlueprintsRequest.SerializeToString,
            communitygames__pb2.GetScheduledBlueprintsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getConstraints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/getConstraints',
            communitygames__pb2.GetConstraintsRequest.SerializeToString,
            communitygames__pb2.GetConstraintsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sharePlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/sharePlayground',
            communitygames__pb2.SharePlaygroundRequest.SerializeToString,
            communitygames__pb2.SharePlaygroundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getProgressionTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.communitygames.CommunityGames/getProgressionTypes',
            communitygames__pb2.GetProgressionTypesRequest.SerializeToString,
            communitygames__pb2.GetProgressionTypesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
