# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: localization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12localization.proto\x12\x10web.localization\"\x17\n\x07SidList\x12\x0c\n\x04sids\x18\x01 \x03(\t\"\x1d\n\x0e\x43\x61tegoryIdList\x12\x0b\n\x03ids\x18\x01 \x03(\x05\" \n\x11SubCategoryIdList\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"\xb9\x01\n\x11TranslationsQuery\x12*\n\x07sidList\x18\x01 \x01(\x0b\x32\x19.web.localization.SidList\x12\x38\n\x0e\x63\x61tegoryIdList\x18\x02 \x01(\x0b\x32 .web.localization.CategoryIdList\x12>\n\x11subCategoryIdList\x18\x03 \x01(\x0b\x32#.web.localization.SubCategoryIdList\"G\n\rLocalizedText\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x15\n\rlocalizedText\x18\x02 \x01(\t\x12\x12\n\ncategoryId\x18\x03 \x01(\x05\"/\n\tTimestamp\x12\x13\n\x07seconds\x18\x01 \x01(\x03\x42\x02\x30\x01\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\x98\x01\n\x16GetTranslationsRequest\x12>\n\x11translationsQuery\x18\x01 \x01(\x0b\x32#.web.localization.TranslationsQuery\x12\x0e\n\x06locale\x18\x04 \x01(\t\x12.\n\tfetchFrom\x18\x05 \x01(\x0b\x32\x1b.web.localization.Timestamp\"\x85\x01\n\x17GetTranslationsResponse\x12\x37\n\x0elocalizedTexts\x18\x03 \x03(\x0b\x32\x1f.web.localization.LocalizedText\x12\x31\n\x0c\x66\x65tchedUntil\x18\x04 \x01(\x0b\x32\x1b.web.localization.Timestamp2~\n\x12\x43lientLocalization\x12h\n\x0fgetTranslations\x12(.web.localization.GetTranslationsRequest\x1a).web.localization.GetTranslationsResponse\"\x00\x62\x06proto3')



_SIDLIST = DESCRIPTOR.message_types_by_name['SidList']
_CATEGORYIDLIST = DESCRIPTOR.message_types_by_name['CategoryIdList']
_SUBCATEGORYIDLIST = DESCRIPTOR.message_types_by_name['SubCategoryIdList']
_TRANSLATIONSQUERY = DESCRIPTOR.message_types_by_name['TranslationsQuery']
_LOCALIZEDTEXT = DESCRIPTOR.message_types_by_name['LocalizedText']
_TIMESTAMP = DESCRIPTOR.message_types_by_name['Timestamp']
_GETTRANSLATIONSREQUEST = DESCRIPTOR.message_types_by_name['GetTranslationsRequest']
_GETTRANSLATIONSRESPONSE = DESCRIPTOR.message_types_by_name['GetTranslationsResponse']
SidList = _reflection.GeneratedProtocolMessageType('SidList', (_message.Message,), {
  'DESCRIPTOR' : _SIDLIST,
  '__module__' : 'localization_pb2'
  # @@protoc_insertion_point(class_scope:web.localization.SidList)
  })
_sym_db.RegisterMessage(SidList)

CategoryIdList = _reflection.GeneratedProtocolMessageType('CategoryIdList', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYIDLIST,
  '__module__' : 'localization_pb2'
  # @@protoc_insertion_point(class_scope:web.localization.CategoryIdList)
  })
_sym_db.RegisterMessage(CategoryIdList)

SubCategoryIdList = _reflection.GeneratedProtocolMessageType('SubCategoryIdList', (_message.Message,), {
  'DESCRIPTOR' : _SUBCATEGORYIDLIST,
  '__module__' : 'localization_pb2'
  # @@protoc_insertion_point(class_scope:web.localization.SubCategoryIdList)
  })
_sym_db.RegisterMessage(SubCategoryIdList)

TranslationsQuery = _reflection.GeneratedProtocolMessageType('TranslationsQuery', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATIONSQUERY,
  '__module__' : 'localization_pb2'
  # @@protoc_insertion_point(class_scope:web.localization.TranslationsQuery)
  })
_sym_db.RegisterMessage(TranslationsQuery)

LocalizedText = _reflection.GeneratedProtocolMessageType('LocalizedText', (_message.Message,), {
  'DESCRIPTOR' : _LOCALIZEDTEXT,
  '__module__' : 'localization_pb2'
  # @@protoc_insertion_point(class_scope:web.localization.LocalizedText)
  })
_sym_db.RegisterMessage(LocalizedText)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'localization_pb2'
  # @@protoc_insertion_point(class_scope:web.localization.Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

GetTranslationsRequest = _reflection.GeneratedProtocolMessageType('GetTranslationsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSLATIONSREQUEST,
  '__module__' : 'localization_pb2'
  # @@protoc_insertion_point(class_scope:web.localization.GetTranslationsRequest)
  })
_sym_db.RegisterMessage(GetTranslationsRequest)

GetTranslationsResponse = _reflection.GeneratedProtocolMessageType('GetTranslationsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSLATIONSRESPONSE,
  '__module__' : 'localization_pb2'
  # @@protoc_insertion_point(class_scope:web.localization.GetTranslationsResponse)
  })
_sym_db.RegisterMessage(GetTranslationsResponse)

_CLIENTLOCALIZATION = DESCRIPTOR.services_by_name['ClientLocalization']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMESTAMP.fields_by_name['seconds']._options = None
  _TIMESTAMP.fields_by_name['seconds']._serialized_options = b'0\001'
  _SIDLIST._serialized_start=40
  _SIDLIST._serialized_end=63
  _CATEGORYIDLIST._serialized_start=65
  _CATEGORYIDLIST._serialized_end=94
  _SUBCATEGORYIDLIST._serialized_start=96
  _SUBCATEGORYIDLIST._serialized_end=128
  _TRANSLATIONSQUERY._serialized_start=131
  _TRANSLATIONSQUERY._serialized_end=316
  _LOCALIZEDTEXT._serialized_start=318
  _LOCALIZEDTEXT._serialized_end=389
  _TIMESTAMP._serialized_start=391
  _TIMESTAMP._serialized_end=438
  _GETTRANSLATIONSREQUEST._serialized_start=441
  _GETTRANSLATIONSREQUEST._serialized_end=593
  _GETTRANSLATIONSRESPONSE._serialized_start=596
  _GETTRANSLATIONSRESPONSE._serialized_end=729
  _CLIENTLOCALIZATION._serialized_start=731
  _CLIENTLOCALIZATION._serialized_end=857
# @@protoc_insertion_point(module_scope)
