# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/reporting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/reporting.proto\x12\rweb.reporting\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"\xd4\x01\n\x17ReportPlaygroundRequest\x12\x17\n\x0fprotocolVersion\x18\x01 \x01(\t\x12\x14\n\x0cplaygroundId\x18\x02 \x01(\t\x12)\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x17.web.reporting.Category\x12\x32\n\x0erequesterEmail\x18\x04 \x01(\x0b\x32\x1a.web.reporting.StringValue\x12+\n\x07subject\x18\x05 \x01(\x0b\x32\x1a.web.reporting.StringValue\".\n\x18ReportPlaygroundResponse\x12\x12\n\npetitionId\x18\x01 \x01(\t*\xc7\x02\n\x08\x43\x61tegory\x12\x14\n\x10UNKNOWN_CATEGORY\x10\x00\x12\x0c\n\x08\x43HEATING\x10\x01\x12\x0e\n\nHARASSMENT\x10\x02\x12\x08\n\x04SPAM\x10\x03\x12\x0e\n\nPLAGIARISM\x10\x04\x12\x0f\n\x0bHATE_SPEECH\x10\x05\x12\x15\n\x11SEXUALLY_EXPLICIT\x10\x06\x12\x16\n\x12\x43HILD_SOLICITATION\x10\x07\x12\x14\n\x10TERRORIST_THREAT\x10\x08\x12\x0f\n\x0b\x43LIENT_HACK\x10\t\x12\x12\n\x0eSUICIDE_THREAT\x10\n\x12\n\n\x06\x44OXING\x10\x0b\x12\x0f\n\x0b\x41\x44VERTISING\x10\x0c\x12\x11\n\rINAPPROPRIATE\x10\r\x12\x0b\n\x07VIOLENT\x10\x0e\x12\r\n\tOFFENSIVE\x10\x0f\x12\x12\n\x0eOFFENSIVE_CHAT\x10\x10\x12\x12\n\x0eOFFENSIVE_NAME\x10\x11\x32u\n\x0cWebReporting\x12\x65\n\x10reportPlayground\x12&.web.reporting.ReportPlaygroundRequest\x1a\'.web.reporting.ReportPlaygroundResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.reporting_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CATEGORY']._serialized_start=334
  _globals['_CATEGORY']._serialized_end=661
  _globals['_STRINGVALUE']._serialized_start=40
  _globals['_STRINGVALUE']._serialized_end=68
  _globals['_REPORTPLAYGROUNDREQUEST']._serialized_start=71
  _globals['_REPORTPLAYGROUNDREQUEST']._serialized_end=283
  _globals['_REPORTPLAYGROUNDRESPONSE']._serialized_start=285
  _globals['_REPORTPLAYGROUNDRESPONSE']._serialized_end=331
  _globals['_WEBREPORTING']._serialized_start=663
  _globals['_WEBREPORTING']._serialized_end=780
# @@protoc_insertion_point(module_scope)
