# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import reporting_pb2 as reporting__pb2


class WebReportingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reportPlayground = channel.unary_unary(
                '/web.reporting.WebReporting/reportPlayground',
                request_serializer=reporting__pb2.ReportPlaygroundRequest.SerializeToString,
                response_deserializer=reporting__pb2.ReportPlaygroundResponse.FromString,
                )


class WebReportingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reportPlayground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebReportingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reportPlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.reportPlayground,
                    request_deserializer=reporting__pb2.ReportPlaygroundRequest.FromString,
                    response_serializer=reporting__pb2.ReportPlaygroundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'web.reporting.WebReporting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WebReporting(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reportPlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/web.reporting.WebReporting/reportPlayground',
            reporting__pb2.ReportPlaygroundRequest.SerializeToString,
            reporting__pb2.ReportPlaygroundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
