# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reporting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freporting.proto\x12\rweb.reporting\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"\xd4\x01\n\x17ReportPlaygroundRequest\x12\x17\n\x0fprotocolVersion\x18\x01 \x01(\t\x12\x14\n\x0cplaygroundId\x18\x02 \x01(\t\x12)\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x17.web.reporting.Category\x12\x32\n\x0erequesterEmail\x18\x04 \x01(\x0b\x32\x1a.web.reporting.StringValue\x12+\n\x07subject\x18\x05 \x01(\x0b\x32\x1a.web.reporting.StringValue\".\n\x18ReportPlaygroundResponse\x12\x12\n\npetitionId\x18\x01 \x01(\t*\xc7\x02\n\x08\x43\x61tegory\x12\x14\n\x10UNKNOWN_CATEGORY\x10\x00\x12\x0c\n\x08\x43HEATING\x10\x01\x12\x0e\n\nHARASSMENT\x10\x02\x12\x08\n\x04SPAM\x10\x03\x12\x0e\n\nPLAGIARISM\x10\x04\x12\x0f\n\x0bHATE_SPEECH\x10\x05\x12\x15\n\x11SEXUALLY_EXPLICIT\x10\x06\x12\x16\n\x12\x43HILD_SOLICITATION\x10\x07\x12\x14\n\x10TERRORIST_THREAT\x10\x08\x12\x0f\n\x0b\x43LIENT_HACK\x10\t\x12\x12\n\x0eSUICIDE_THREAT\x10\n\x12\n\n\x06\x44OXING\x10\x0b\x12\x0f\n\x0b\x41\x44VERTISING\x10\x0c\x12\x11\n\rINAPPROPRIATE\x10\r\x12\x0b\n\x07VIOLENT\x10\x0e\x12\r\n\tOFFENSIVE\x10\x0f\x12\x12\n\x0eOFFENSIVE_CHAT\x10\x10\x12\x12\n\x0eOFFENSIVE_NAME\x10\x11\x32u\n\x0cWebReporting\x12\x65\n\x10reportPlayground\x12&.web.reporting.ReportPlaygroundRequest\x1a\'.web.reporting.ReportPlaygroundResponse\"\x00\x62\x06proto3')

_CATEGORY = DESCRIPTOR.enum_types_by_name['Category']
Category = enum_type_wrapper.EnumTypeWrapper(_CATEGORY)
UNKNOWN_CATEGORY = 0
CHEATING = 1
HARASSMENT = 2
SPAM = 3
PLAGIARISM = 4
HATE_SPEECH = 5
SEXUALLY_EXPLICIT = 6
CHILD_SOLICITATION = 7
TERRORIST_THREAT = 8
CLIENT_HACK = 9
SUICIDE_THREAT = 10
DOXING = 11
ADVERTISING = 12
INAPPROPRIATE = 13
VIOLENT = 14
OFFENSIVE = 15
OFFENSIVE_CHAT = 16
OFFENSIVE_NAME = 17


_STRINGVALUE = DESCRIPTOR.message_types_by_name['StringValue']
_REPORTPLAYGROUNDREQUEST = DESCRIPTOR.message_types_by_name['ReportPlaygroundRequest']
_REPORTPLAYGROUNDRESPONSE = DESCRIPTOR.message_types_by_name['ReportPlaygroundResponse']
StringValue = _reflection.GeneratedProtocolMessageType('StringValue', (_message.Message,), {
  'DESCRIPTOR' : _STRINGVALUE,
  '__module__' : 'reporting_pb2'
  # @@protoc_insertion_point(class_scope:web.reporting.StringValue)
  })
_sym_db.RegisterMessage(StringValue)

ReportPlaygroundRequest = _reflection.GeneratedProtocolMessageType('ReportPlaygroundRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPORTPLAYGROUNDREQUEST,
  '__module__' : 'reporting_pb2'
  # @@protoc_insertion_point(class_scope:web.reporting.ReportPlaygroundRequest)
  })
_sym_db.RegisterMessage(ReportPlaygroundRequest)

ReportPlaygroundResponse = _reflection.GeneratedProtocolMessageType('ReportPlaygroundResponse', (_message.Message,), {
  'DESCRIPTOR' : _REPORTPLAYGROUNDRESPONSE,
  '__module__' : 'reporting_pb2'
  # @@protoc_insertion_point(class_scope:web.reporting.ReportPlaygroundResponse)
  })
_sym_db.RegisterMessage(ReportPlaygroundResponse)

_WEBREPORTING = DESCRIPTOR.services_by_name['WebReporting']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATEGORY._serialized_start=328
  _CATEGORY._serialized_end=655
  _STRINGVALUE._serialized_start=34
  _STRINGVALUE._serialized_end=62
  _REPORTPLAYGROUNDREQUEST._serialized_start=65
  _REPORTPLAYGROUNDREQUEST._serialized_end=277
  _REPORTPLAYGROUNDRESPONSE._serialized_start=279
  _REPORTPLAYGROUNDRESPONSE._serialized_end=325
  _WEBREPORTING._serialized_start=657
  _WEBREPORTING._serialized_end=774
# @@protoc_insertion_point(module_scope)
