// source: proto/localization.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.web.localization.CategoryIdList', null, global);
goog.exportSymbol('proto.web.localization.GetTranslationsRequest', null, global);
goog.exportSymbol('proto.web.localization.GetTranslationsResponse', null, global);
goog.exportSymbol('proto.web.localization.LocalizedText', null, global);
goog.exportSymbol('proto.web.localization.SidList', null, global);
goog.exportSymbol('proto.web.localization.SubCategoryIdList', null, global);
goog.exportSymbol('proto.web.localization.Timestamp', null, global);
goog.exportSymbol('proto.web.localization.TranslationsQuery', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.web.localization.SidList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.web.localization.SidList.repeatedFields_, null);
};
goog.inherits(proto.web.localization.SidList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.web.localization.SidList.displayName = 'proto.web.localization.SidList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.web.localization.CategoryIdList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.web.localization.CategoryIdList.repeatedFields_, null);
};
goog.inherits(proto.web.localization.CategoryIdList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.web.localization.CategoryIdList.displayName = 'proto.web.localization.CategoryIdList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.web.localization.SubCategoryIdList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.web.localization.SubCategoryIdList.repeatedFields_, null);
};
goog.inherits(proto.web.localization.SubCategoryIdList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.web.localization.SubCategoryIdList.displayName = 'proto.web.localization.SubCategoryIdList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.web.localization.TranslationsQuery = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.web.localization.TranslationsQuery, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.web.localization.TranslationsQuery.displayName = 'proto.web.localization.TranslationsQuery';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.web.localization.LocalizedText = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.web.localization.LocalizedText, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.web.localization.LocalizedText.displayName = 'proto.web.localization.LocalizedText';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.web.localization.Timestamp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.web.localization.Timestamp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.web.localization.Timestamp.displayName = 'proto.web.localization.Timestamp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.web.localization.GetTranslationsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.web.localization.GetTranslationsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.web.localization.GetTranslationsRequest.displayName = 'proto.web.localization.GetTranslationsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.web.localization.GetTranslationsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.web.localization.GetTranslationsResponse.repeatedFields_, null);
};
goog.inherits(proto.web.localization.GetTranslationsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.web.localization.GetTranslationsResponse.displayName = 'proto.web.localization.GetTranslationsResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.web.localization.SidList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.web.localization.SidList.prototype.toObject = function(opt_includeInstance) {
  return proto.web.localization.SidList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.web.localization.SidList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.SidList.toObject = function(includeInstance, msg) {
  var f, obj = {
    sidsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.web.localization.SidList}
 */
proto.web.localization.SidList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.web.localization.SidList;
  return proto.web.localization.SidList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.web.localization.SidList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.web.localization.SidList}
 */
proto.web.localization.SidList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addSids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.web.localization.SidList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.web.localization.SidList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.web.localization.SidList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.SidList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSidsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string sids = 1;
 * @return {!Array<string>}
 */
proto.web.localization.SidList.prototype.getSidsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.web.localization.SidList} returns this
 */
proto.web.localization.SidList.prototype.setSidsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.web.localization.SidList} returns this
 */
proto.web.localization.SidList.prototype.addSids = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.web.localization.SidList} returns this
 */
proto.web.localization.SidList.prototype.clearSidsList = function() {
  return this.setSidsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.web.localization.CategoryIdList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.web.localization.CategoryIdList.prototype.toObject = function(opt_includeInstance) {
  return proto.web.localization.CategoryIdList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.web.localization.CategoryIdList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.CategoryIdList.toObject = function(includeInstance, msg) {
  var f, obj = {
    idsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.web.localization.CategoryIdList}
 */
proto.web.localization.CategoryIdList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.web.localization.CategoryIdList;
  return proto.web.localization.CategoryIdList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.web.localization.CategoryIdList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.web.localization.CategoryIdList}
 */
proto.web.localization.CategoryIdList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setIdsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.web.localization.CategoryIdList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.web.localization.CategoryIdList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.web.localization.CategoryIdList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.CategoryIdList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      1,
      f
    );
  }
};


/**
 * repeated int32 ids = 1;
 * @return {!Array<number>}
 */
proto.web.localization.CategoryIdList.prototype.getIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.web.localization.CategoryIdList} returns this
 */
proto.web.localization.CategoryIdList.prototype.setIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.web.localization.CategoryIdList} returns this
 */
proto.web.localization.CategoryIdList.prototype.addIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.web.localization.CategoryIdList} returns this
 */
proto.web.localization.CategoryIdList.prototype.clearIdsList = function() {
  return this.setIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.web.localization.SubCategoryIdList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.web.localization.SubCategoryIdList.prototype.toObject = function(opt_includeInstance) {
  return proto.web.localization.SubCategoryIdList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.web.localization.SubCategoryIdList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.SubCategoryIdList.toObject = function(includeInstance, msg) {
  var f, obj = {
    idsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.web.localization.SubCategoryIdList}
 */
proto.web.localization.SubCategoryIdList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.web.localization.SubCategoryIdList;
  return proto.web.localization.SubCategoryIdList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.web.localization.SubCategoryIdList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.web.localization.SubCategoryIdList}
 */
proto.web.localization.SubCategoryIdList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setIdsList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.web.localization.SubCategoryIdList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.web.localization.SubCategoryIdList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.web.localization.SubCategoryIdList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.SubCategoryIdList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      1,
      f
    );
  }
};


/**
 * repeated int32 ids = 1;
 * @return {!Array<number>}
 */
proto.web.localization.SubCategoryIdList.prototype.getIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.web.localization.SubCategoryIdList} returns this
 */
proto.web.localization.SubCategoryIdList.prototype.setIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.web.localization.SubCategoryIdList} returns this
 */
proto.web.localization.SubCategoryIdList.prototype.addIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.web.localization.SubCategoryIdList} returns this
 */
proto.web.localization.SubCategoryIdList.prototype.clearIdsList = function() {
  return this.setIdsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.web.localization.TranslationsQuery.prototype.toObject = function(opt_includeInstance) {
  return proto.web.localization.TranslationsQuery.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.web.localization.TranslationsQuery} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.TranslationsQuery.toObject = function(includeInstance, msg) {
  var f, obj = {
    sidlist: (f = msg.getSidlist()) && proto.web.localization.SidList.toObject(includeInstance, f),
    categoryidlist: (f = msg.getCategoryidlist()) && proto.web.localization.CategoryIdList.toObject(includeInstance, f),
    subcategoryidlist: (f = msg.getSubcategoryidlist()) && proto.web.localization.SubCategoryIdList.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.web.localization.TranslationsQuery}
 */
proto.web.localization.TranslationsQuery.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.web.localization.TranslationsQuery;
  return proto.web.localization.TranslationsQuery.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.web.localization.TranslationsQuery} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.web.localization.TranslationsQuery}
 */
proto.web.localization.TranslationsQuery.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.web.localization.SidList;
      reader.readMessage(value,proto.web.localization.SidList.deserializeBinaryFromReader);
      msg.setSidlist(value);
      break;
    case 2:
      var value = new proto.web.localization.CategoryIdList;
      reader.readMessage(value,proto.web.localization.CategoryIdList.deserializeBinaryFromReader);
      msg.setCategoryidlist(value);
      break;
    case 3:
      var value = new proto.web.localization.SubCategoryIdList;
      reader.readMessage(value,proto.web.localization.SubCategoryIdList.deserializeBinaryFromReader);
      msg.setSubcategoryidlist(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.web.localization.TranslationsQuery.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.web.localization.TranslationsQuery.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.web.localization.TranslationsQuery} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.TranslationsQuery.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSidlist();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.web.localization.SidList.serializeBinaryToWriter
    );
  }
  f = message.getCategoryidlist();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.web.localization.CategoryIdList.serializeBinaryToWriter
    );
  }
  f = message.getSubcategoryidlist();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.web.localization.SubCategoryIdList.serializeBinaryToWriter
    );
  }
};


/**
 * optional SidList sidList = 1;
 * @return {?proto.web.localization.SidList}
 */
proto.web.localization.TranslationsQuery.prototype.getSidlist = function() {
  return /** @type{?proto.web.localization.SidList} */ (
    jspb.Message.getWrapperField(this, proto.web.localization.SidList, 1));
};


/**
 * @param {?proto.web.localization.SidList|undefined} value
 * @return {!proto.web.localization.TranslationsQuery} returns this
*/
proto.web.localization.TranslationsQuery.prototype.setSidlist = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.web.localization.TranslationsQuery} returns this
 */
proto.web.localization.TranslationsQuery.prototype.clearSidlist = function() {
  return this.setSidlist(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.web.localization.TranslationsQuery.prototype.hasSidlist = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CategoryIdList categoryIdList = 2;
 * @return {?proto.web.localization.CategoryIdList}
 */
proto.web.localization.TranslationsQuery.prototype.getCategoryidlist = function() {
  return /** @type{?proto.web.localization.CategoryIdList} */ (
    jspb.Message.getWrapperField(this, proto.web.localization.CategoryIdList, 2));
};


/**
 * @param {?proto.web.localization.CategoryIdList|undefined} value
 * @return {!proto.web.localization.TranslationsQuery} returns this
*/
proto.web.localization.TranslationsQuery.prototype.setCategoryidlist = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.web.localization.TranslationsQuery} returns this
 */
proto.web.localization.TranslationsQuery.prototype.clearCategoryidlist = function() {
  return this.setCategoryidlist(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.web.localization.TranslationsQuery.prototype.hasCategoryidlist = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SubCategoryIdList subCategoryIdList = 3;
 * @return {?proto.web.localization.SubCategoryIdList}
 */
proto.web.localization.TranslationsQuery.prototype.getSubcategoryidlist = function() {
  return /** @type{?proto.web.localization.SubCategoryIdList} */ (
    jspb.Message.getWrapperField(this, proto.web.localization.SubCategoryIdList, 3));
};


/**
 * @param {?proto.web.localization.SubCategoryIdList|undefined} value
 * @return {!proto.web.localization.TranslationsQuery} returns this
*/
proto.web.localization.TranslationsQuery.prototype.setSubcategoryidlist = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.web.localization.TranslationsQuery} returns this
 */
proto.web.localization.TranslationsQuery.prototype.clearSubcategoryidlist = function() {
  return this.setSubcategoryidlist(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.web.localization.TranslationsQuery.prototype.hasSubcategoryidlist = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.web.localization.LocalizedText.prototype.toObject = function(opt_includeInstance) {
  return proto.web.localization.LocalizedText.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.web.localization.LocalizedText} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.LocalizedText.toObject = function(includeInstance, msg) {
  var f, obj = {
    sid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    localizedtext: jspb.Message.getFieldWithDefault(msg, 2, ""),
    categoryid: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.web.localization.LocalizedText}
 */
proto.web.localization.LocalizedText.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.web.localization.LocalizedText;
  return proto.web.localization.LocalizedText.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.web.localization.LocalizedText} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.web.localization.LocalizedText}
 */
proto.web.localization.LocalizedText.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocalizedtext(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCategoryid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.web.localization.LocalizedText.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.web.localization.LocalizedText.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.web.localization.LocalizedText} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.LocalizedText.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLocalizedtext();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCategoryid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string sid = 1;
 * @return {string}
 */
proto.web.localization.LocalizedText.prototype.getSid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.web.localization.LocalizedText} returns this
 */
proto.web.localization.LocalizedText.prototype.setSid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string localizedText = 2;
 * @return {string}
 */
proto.web.localization.LocalizedText.prototype.getLocalizedtext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.web.localization.LocalizedText} returns this
 */
proto.web.localization.LocalizedText.prototype.setLocalizedtext = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 categoryId = 3;
 * @return {number}
 */
proto.web.localization.LocalizedText.prototype.getCategoryid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.web.localization.LocalizedText} returns this
 */
proto.web.localization.LocalizedText.prototype.setCategoryid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.web.localization.Timestamp.prototype.toObject = function(opt_includeInstance) {
  return proto.web.localization.Timestamp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.web.localization.Timestamp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.Timestamp.toObject = function(includeInstance, msg) {
  var f, obj = {
    seconds: jspb.Message.getFieldWithDefault(msg, 1, "0"),
    nanos: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.web.localization.Timestamp}
 */
proto.web.localization.Timestamp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.web.localization.Timestamp;
  return proto.web.localization.Timestamp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.web.localization.Timestamp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.web.localization.Timestamp}
 */
proto.web.localization.Timestamp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readInt64String());
      msg.setSeconds(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNanos(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.web.localization.Timestamp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.web.localization.Timestamp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.web.localization.Timestamp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.Timestamp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSeconds();
  if (parseInt(f, 10) !== 0) {
    writer.writeInt64String(
      1,
      f
    );
  }
  f = message.getNanos();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int64 seconds = 1;
 * @return {string}
 */
proto.web.localization.Timestamp.prototype.getSeconds = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, "0"));
};


/**
 * @param {string} value
 * @return {!proto.web.localization.Timestamp} returns this
 */
proto.web.localization.Timestamp.prototype.setSeconds = function(value) {
  return jspb.Message.setProto3StringIntField(this, 1, value);
};


/**
 * optional int32 nanos = 2;
 * @return {number}
 */
proto.web.localization.Timestamp.prototype.getNanos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.web.localization.Timestamp} returns this
 */
proto.web.localization.Timestamp.prototype.setNanos = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.web.localization.GetTranslationsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.web.localization.GetTranslationsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.web.localization.GetTranslationsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.GetTranslationsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    translationsquery: (f = msg.getTranslationsquery()) && proto.web.localization.TranslationsQuery.toObject(includeInstance, f),
    locale: jspb.Message.getFieldWithDefault(msg, 4, ""),
    fetchfrom: (f = msg.getFetchfrom()) && proto.web.localization.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.web.localization.GetTranslationsRequest}
 */
proto.web.localization.GetTranslationsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.web.localization.GetTranslationsRequest;
  return proto.web.localization.GetTranslationsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.web.localization.GetTranslationsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.web.localization.GetTranslationsRequest}
 */
proto.web.localization.GetTranslationsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.web.localization.TranslationsQuery;
      reader.readMessage(value,proto.web.localization.TranslationsQuery.deserializeBinaryFromReader);
      msg.setTranslationsquery(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocale(value);
      break;
    case 5:
      var value = new proto.web.localization.Timestamp;
      reader.readMessage(value,proto.web.localization.Timestamp.deserializeBinaryFromReader);
      msg.setFetchfrom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.web.localization.GetTranslationsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.web.localization.GetTranslationsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.web.localization.GetTranslationsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.GetTranslationsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTranslationsquery();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.web.localization.TranslationsQuery.serializeBinaryToWriter
    );
  }
  f = message.getLocale();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFetchfrom();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.web.localization.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional TranslationsQuery translationsQuery = 1;
 * @return {?proto.web.localization.TranslationsQuery}
 */
proto.web.localization.GetTranslationsRequest.prototype.getTranslationsquery = function() {
  return /** @type{?proto.web.localization.TranslationsQuery} */ (
    jspb.Message.getWrapperField(this, proto.web.localization.TranslationsQuery, 1));
};


/**
 * @param {?proto.web.localization.TranslationsQuery|undefined} value
 * @return {!proto.web.localization.GetTranslationsRequest} returns this
*/
proto.web.localization.GetTranslationsRequest.prototype.setTranslationsquery = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.web.localization.GetTranslationsRequest} returns this
 */
proto.web.localization.GetTranslationsRequest.prototype.clearTranslationsquery = function() {
  return this.setTranslationsquery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.web.localization.GetTranslationsRequest.prototype.hasTranslationsquery = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string locale = 4;
 * @return {string}
 */
proto.web.localization.GetTranslationsRequest.prototype.getLocale = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.web.localization.GetTranslationsRequest} returns this
 */
proto.web.localization.GetTranslationsRequest.prototype.setLocale = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Timestamp fetchFrom = 5;
 * @return {?proto.web.localization.Timestamp}
 */
proto.web.localization.GetTranslationsRequest.prototype.getFetchfrom = function() {
  return /** @type{?proto.web.localization.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.web.localization.Timestamp, 5));
};


/**
 * @param {?proto.web.localization.Timestamp|undefined} value
 * @return {!proto.web.localization.GetTranslationsRequest} returns this
*/
proto.web.localization.GetTranslationsRequest.prototype.setFetchfrom = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.web.localization.GetTranslationsRequest} returns this
 */
proto.web.localization.GetTranslationsRequest.prototype.clearFetchfrom = function() {
  return this.setFetchfrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.web.localization.GetTranslationsRequest.prototype.hasFetchfrom = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.web.localization.GetTranslationsResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.web.localization.GetTranslationsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.web.localization.GetTranslationsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.web.localization.GetTranslationsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.GetTranslationsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    localizedtextsList: jspb.Message.toObjectList(msg.getLocalizedtextsList(),
    proto.web.localization.LocalizedText.toObject, includeInstance),
    fetcheduntil: (f = msg.getFetcheduntil()) && proto.web.localization.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.web.localization.GetTranslationsResponse}
 */
proto.web.localization.GetTranslationsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.web.localization.GetTranslationsResponse;
  return proto.web.localization.GetTranslationsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.web.localization.GetTranslationsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.web.localization.GetTranslationsResponse}
 */
proto.web.localization.GetTranslationsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = new proto.web.localization.LocalizedText;
      reader.readMessage(value,proto.web.localization.LocalizedText.deserializeBinaryFromReader);
      msg.addLocalizedtexts(value);
      break;
    case 4:
      var value = new proto.web.localization.Timestamp;
      reader.readMessage(value,proto.web.localization.Timestamp.deserializeBinaryFromReader);
      msg.setFetcheduntil(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.web.localization.GetTranslationsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.web.localization.GetTranslationsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.web.localization.GetTranslationsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.web.localization.GetTranslationsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocalizedtextsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.web.localization.LocalizedText.serializeBinaryToWriter
    );
  }
  f = message.getFetcheduntil();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.web.localization.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * repeated LocalizedText localizedTexts = 3;
 * @return {!Array<!proto.web.localization.LocalizedText>}
 */
proto.web.localization.GetTranslationsResponse.prototype.getLocalizedtextsList = function() {
  return /** @type{!Array<!proto.web.localization.LocalizedText>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.web.localization.LocalizedText, 3));
};


/**
 * @param {!Array<!proto.web.localization.LocalizedText>} value
 * @return {!proto.web.localization.GetTranslationsResponse} returns this
*/
proto.web.localization.GetTranslationsResponse.prototype.setLocalizedtextsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.web.localization.LocalizedText=} opt_value
 * @param {number=} opt_index
 * @return {!proto.web.localization.LocalizedText}
 */
proto.web.localization.GetTranslationsResponse.prototype.addLocalizedtexts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.web.localization.LocalizedText, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.web.localization.GetTranslationsResponse} returns this
 */
proto.web.localization.GetTranslationsResponse.prototype.clearLocalizedtextsList = function() {
  return this.setLocalizedtextsList([]);
};


/**
 * optional Timestamp fetchedUntil = 4;
 * @return {?proto.web.localization.Timestamp}
 */
proto.web.localization.GetTranslationsResponse.prototype.getFetcheduntil = function() {
  return /** @type{?proto.web.localization.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.web.localization.Timestamp, 4));
};


/**
 * @param {?proto.web.localization.Timestamp|undefined} value
 * @return {!proto.web.localization.GetTranslationsResponse} returns this
*/
proto.web.localization.GetTranslationsResponse.prototype.setFetcheduntil = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.web.localization.GetTranslationsResponse} returns this
 */
proto.web.localization.GetTranslationsResponse.prototype.clearFetcheduntil = function() {
  return this.setFetcheduntil(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.web.localization.GetTranslationsResponse.prototype.hasFetcheduntil = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.web.localization);
