export { ClientAuthenticationClient } from './proto/AuthenticationServiceClientPb'
export * as authentication from './proto/authentication_pb'
export { CommunityGamesClient } from './proto/CommunitygamesServiceClientPb'
export * as communitygames from './proto/communitygames_pb'
export { ClientLocalizationClient } from './proto/LocalizationServiceClientPb'
export * as localization from './proto/localization_pb'
export { WebReportingClient } from './proto/ReportingServiceClientPb'
export * as reporting from './proto/reporting_pb'
